server:
  port: 8088

logging:
  level:
    org.springframework: info

spring:
  jpa:
    show-sql: true
  messages:
    basename: messages
  security:
    user:
      name: bomb
      password: qwer1234


management:
  endpoints:
    web:
      exposure:
        include: "*"
